##language:react
##type:action
##operation:deploy to netlify
name: "Deploy to Netlify"
description: "Deploy built site to Netlify"

inputs:
  site-id:
    description: "Netlify site ID"
    required: true
  auth-token:
    description: "Netlify auth token"
    required: true
  build-dir:
    description: "Path to build directory"
    required: false
    default: "build"

runs:
  using: "composite"
  steps:
    - name: Install Netlify CLI
      shell: bash
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      shell: bash
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.auth-token }}
        NETLIFY_SITE_ID: ${{ inputs.site-id }}
      run: netlify deploy --dir=${{ inputs.build-dir }} --prod
