##language:go
##type:simple workflow
##operation:version
name: Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25.0-alpine3.22
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display Go version
        run: go version
