##language:react
##type:workflow with action
##operation:build test deploy
name: Build, Test, and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build React app
        id: build
        uses: ./.github/actions/build-react

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test React app
        uses: ./.github/actions/test-react

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Deploy to Netlify
        uses: ./.github/actions/deploy-netlify
        with:
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          build-dir: build
